#!/bin/bash

# create tmp folder for vim swp
mkdir ~/tmp

# install tmux
apt-get install vim tmux

# install pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle;

curl -Sso ~/.vim/autoload/pathogen.vim \
https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

# install NERDTree
cd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git

# link the files
cd ~
ln -s ~/personal/dotfiles/.vimrc .
ln -s ~/personal/dotfiles/.tmux.conf .
ln -s ~/personal/dotfiles/.bash_aliases .
