#!/bin/bash

# create tmp folder for vim swp
mkdir ~/tmp

# install pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle;

curl -Sso ~/.vim/autoload/pathogen.vim \
https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

# install NERDTree
cd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git

# install NERDTreeTabs
cd ~/.vim/bundle
git clone https://github.com/jistr/vim-nerdtree-tabs.git

# install tagbar
cd ~/.vim/bundle
git clone git://github.com/majutsushi/tagbar

# install AutoTag
cd ~/.vim/bundle
git clone https://github.com/vim-scripts/AutoTag.git

#install ctrlp - fuzzy search
cd ~/.vim/bundle
git clone https://github.com/kien/ctrlp.vim.git ctrlp/ctrlp.vim

# link the files
cd ~
ln -s ~/personal/dotfiles/.vimrc .
ln -s ~/personal/dotfiles/.tmux.conf .
ln -s ~/personal/dotfiles/.bash_aliases .
