#!/bin/bash

# create vim folders
mkdir ~/tmp
mkdir -p ~/.vim/autoload ~/.vim/bundle;

# copy our colors dir in
cp -R ./colors ~/.vim/

# install pathogen
curl -Sso ~/.vim/autoload/pathogen.vim \
https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

# install airline
git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline

# install NERDTree
cd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git

# install NERDTreeTabs
cd ~/.vim/bundle
git clone https://github.com/jistr/vim-nerdtree-tabs.git

# install tagbar
cd ~/.vim/bundle
git clone git://github.com/majutsushi/tagbar

# install AutoTag
cd ~/.vim/bundle
git clone https://github.com/vim-scripts/AutoTag.git

# relative numbering switcher
cd ~/.vim/bundle
git clone https://github.com/jeffkreeftmeijer/vim-numbertoggle.git

#install ctrlp - fuzzy search
cd ~/.vim/bundle
git clone https://github.com/kien/ctrlp.vim.git ctrlp/ctrlp.vim

# install syntastic
cd ~/.vim/bundle
git clone https://github.com/scrooloose/syntastic.git

# install delimitMat - auto-insert quotes,params,brackets
cd ~/.vim/bundle
git clone https://github.com/Raimondi/delimitMate.git

# install YouCompleteMe, best fucking thing on the planet
cd ~/.vim/bundle
git clone https://github.com/Valloric/YouCompleteMe.git
cd YouCompleteMe
git submodule update --init --recursive

# link the files
cd ~
ln -s ~/personal/dotfiles/.vimrc .

# install color themes
cd ~/.vim/bundle
git clone git://github.com/altercation/vim-colors-solarized.git
~/personal/dotfiles/solarize.sh dark

cd ~/.vim
mkdir vim-colors
cd ~/.vim/colors
wget https://raw.githubusercontent.com/tomasr/dotfiles/master/.vim/colors/wombat.vim

# Setup bash
./bash/bash-setup.sh

# Setup tmux
./tmux/tmux-setup.sh
