#!/bin/bash

# create vim folders
mkdir -p ~/.vim/autoload ~/.vim/bundle;

cd ~/.vim/autoload

# install pathogen
curl -LSso ~/.vim/autoload/pathogen.vim \
https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

cd ~/.vim/bundle

# install airline
git clone https://github.com/bling/vim-airline ~/.vim/bundle/vim-airline

# install NERDTree
git clone https://github.com/scrooloose/nerdtree.git

# install NERDTreeTabs
git clone https://github.com/jistr/vim-nerdtree-tabs.git

# install gitgutter
git clone git://github.com/airblade/vim-gitgutter.git

# relative numbering switcher
git clone https://github.com/jeffkreeftmeijer/vim-numbertoggle.git

#install ctrlp - fuzzy search
git clone https://github.com/kien/ctrlp.vim.git ctrlp/ctrlp.vim

# install syntastic
git clone https://github.com/scrooloose/syntastic.git

# install delimitMat - auto-insert quotes,params,brackets
git clone https://github.com/Raimondi/delimitMate.git

# install YouCompleteMe, best fucking thing on the planet
git clone https://github.com/Valloric/YouCompleteMe.git
cd YouCompleteMe
git submodule update --init --recursive

# link the files
cd ~
ln -s ~/personal/dotfiles/vim/.vimrc .
